version: '3.1'

services:
  nextjs-tutorial-frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/frontend/Dockerfile
      image: tomkiel/nextjs-tutorial-frontend
    container_name: nextjs-tutorial-frontend
    ports:
      - "3000:3000"