import type { Metadata } from 'next'
import '@styles/main.scss';

export const metadata: Metadata = {
  title: 'My Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
