version: "3.1"

services:
  nextjs-tutorial-nginx:
    image: nginx:1-alpine
    container_name: nextjs-tutorial-nginx
    ports:
      - "80:80"
    volumes:
    - "../../frontend/.next/cache/images/:/var/data/images"
    - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    - "./conf/sites-enabled/:/etc/nginx/sites-enabled/"

