version: '3'

services:
  nextjs-tutorial-database:
    env_file:
      - ../../.env
    image: postgres:16-alpine
    container_name: nextjs-tutorial-database
    environment:
      POSTGRES_CONFIG_FILE: ./conf/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - nextjs_tutorial_db_data:/var/lib/postgresql/data

volumes:
  nextjs_tutorial_db_data:
